/*
 * DO NOT EDIT THIS FILE
 *
 * Use this as a source to figure out the needs to fill in letter-count.js
 *
*/
const test = require('tape');
const counter = require('./letter-count');

const corpus = 'my cat is somewhat derpy';

test('reports the number of times the letter appears in the text', t => {
  const count = counter(corpus, 'w');
  t.equal(count, 1);
  t.end();
});

test('runs with no matches', t => {
  const count = counter(corpus, 'z');
  t.equal( count, 0 );
  t.end();
});

test('runs with multiple matches', t => {
  const count = counter(corpus, 'a');
  t.equal( count, 2 );
  t.end();
});

